const authEvents = require('./auth/events')
const hikeEvents = require('./hike/events')
// const ui = require('./hike/ui')

$(() => {
  $('#sign-up').on('submit', authEvents.signUp)
  $('#sign-in').on('submit', authEvents.signIn)
  $('#sign-out').on('click', authEvents.signOut)
  $('#change-password').on('submit', authEvents.changePassword)
  $('#log-hike').on('submit', hikeEvents.logHike)
  $('#view-hikes').on('click', hikeEvents.viewHike)
  $('#showSingleHike').on('click', '.delete-hike', hikeEvents.deleteHike)
  $('#hikesHtml').on('click', '.view-hike', hikeEvents.showHike)
  $('#showSingleHike').on('click', '.edit-hike', hikeEvents.editHike)
  $('.changePassword').on('click', hikeEvents.changeView)
  $('.hikeLogger').on('click', hikeEvents.changeView)
  $('#home').on('click', hikeEvents.changeView)
  $('.viewHikes').on('click', hikeEvents.changeView)
  $('#not-user').on('click', authEvents.notUser)
  $('#already-user').on('click', authEvents.alreadyUser)
})

$(() => {
  $('#changePasswordBox').hide()
  $('#log-hike').hide()
  $('#sign-out').hide()
  $('#view-hikes').hide()
  $('.topnav').hide()
  $('.signUp-box').hide()
  $('#hikeLogger').hide()
  $('#showSingleHike').hide()
})
